### ISSUE TITLE
Image for docs website?

### ISSUE THREAD

**Issue by nhirschey** [nhirschey/FSharp.Data.Fred#6]
It would be nice to have some sort of image or graphic. Could be a plotly.net line chart of an interest rate series, but that’d probably be hard to see. Maybe some sort of graphic is better. 

Any ideas @DavideGCosta?

**Comment by DavideGCosta** [comment]
@nhirschey
It would be interesting to insert a plot with the 10-Year Treasury Constant Maturity Rate.
But it will be hard to see. So we could also use a histogram of S&P500 returns distribution.

**Comment by nhirschey** [comment]
https://github.com/nhirschey/FSharp.Data.Fred/pull/10
